"""
setup_test_accounts.py
----------------------
Run ONCE before test_contract.py.

What it does:
  1. Generates 5 fresh Algorand accounts:
       admin (= contract creator — must match deployer)
       operator
       verifier
       recycler
       buyer  (used as a dummy address in some calls)

  2. Prints each mnemonic + address.

  3. Funds operator / verifier / recycler / buyer via the
     TestNet Dispenser API (https://bank.testnet.algorand.network).
     admin is NOT funded here — you fund it from your existing
     deployer/creator account (import that mnemonic into .env manually).

  4. Writes a .env file at pillar-1/.env.test with all the keys
     ready for test_contract.py to load.

IMPORTANT
---------
  - The ADMIN account MUST be the same account that deployed the contract
    (App ID 770956001). That account is the Global.creator_address the
    contract checks for "only admin" guards.
  - Replace ADMIN_MNEMONIC in .env.test with your deployer mnemonic.
  - Fund the admin account separately if needed (algokit dispenser or
    https://bank.testnet.algorand.network).

Usage:
  python setup_test_accounts.py
"""

import json
import time
import urllib.request
import urllib.error
from algosdk import account, mnemonic
from algosdk.v2client import algod

# ── Config ────────────────────────────────────────────────────────────────────

APP_ID = 770956001
ALGOD_URL = "https://testnet-api.algonode.cloud"
ALGOD_TOKEN = ""          # Algonode public endpoint needs no token
DISPENSER_URL = "https://bank.testnet.algorand.network"
MIN_BALANCE = 2_000_000   # 2 ALGO in microALGO — enough for box MBR + fees
ENV_OUT = "pillar-1/.env.test"

# ── Helpers ───────────────────────────────────────────────────────────────────

def gen_account():
    private_key, address = account.generate_account()
    mn = mnemonic.from_private_key(private_key)
    return {"address": address, "mnemonic": mn, "private_key": private_key}


def fund_via_dispenser(address: str, amount: int = MIN_BALANCE):
    """Hit the TestNet bank dispenser."""
    url = f"{DISPENSER_URL}/?receiver={address}&amount={amount}"
    try:
        with urllib.request.urlopen(url, timeout=15) as resp:
            body = resp.read().decode()
            print(f"    Dispenser response: {body[:120]}")
            return True
    except urllib.error.HTTPError as e:
        print(f"    Dispenser HTTP error {e.code}: {e.read().decode()[:120]}")
        return False
    except Exception as e:
        print(f"    Dispenser error: {e}")
        return False


def wait_for_balance(client: algod.AlgodClient, address: str, min_bal: int = 100_000, retries: int = 12):
    """Poll until account balance >= min_bal (microALGO)."""
    for i in range(retries):
        try:
            info = client.account_info(address)
            bal = info.get("amount", 0)
            if bal >= min_bal:
                print(f"    ✅ Balance confirmed: {bal / 1e6:.3f} ALGO")
                return True
        except Exception:
            pass
        print(f"    Waiting for funds... ({i+1}/{retries})")
        time.sleep(5)
    print(f"    ⚠️  Balance not confirmed after {retries} retries. Proceed manually.")
    return False

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    client = algod.AlgodClient(ALGOD_TOKEN, ALGOD_URL)

    roles = ["operator", "verifier", "recycler", "buyer"]
    accounts = {role: gen_account() for role in roles}

    print("\n" + "="*60)
    print("Generated accounts (SAVE THESE MNEMONICS SECURELY)")
    print("="*60)
    for role, acct in accounts.items():
        print(f"\n[{role.upper()}]")
        print(f"  Address  : {acct['address']}")
        print(f"  Mnemonic : {acct['mnemonic']}")

    print("\n" + "="*60)
    print("Funding via TestNet Dispenser...")
    print("="*60)
    for role, acct in accounts.items():
        print(f"\nFunding {role}: {acct['address']}")
        ok = fund_via_dispenser(acct['address'])
        if ok:
            wait_for_balance(client, acct['address'])
        else:
            print(f"  ❌ Auto-fund failed. Fund manually:")
            print(f"     https://bank.testnet.algorand.network/?receiver={acct['address']}&amount={MIN_BALANCE}")

    print("\n" + "="*60)
    print(f"Writing {ENV_OUT}")
    print("="*60)

    env_lines = [
        "# Trace-Loop TestNet test accounts",
        "# Generated by setup_test_accounts.py",
        "# ─────────────────────────────────────────────────────",
        f"APP_ID={APP_ID}",
        f"ALGOD_URL={ALGOD_URL}",
        "ALGOD_TOKEN=",
        "",
        "# IMPORTANT: Replace this with your actual deployer mnemonic.",
        "# Admin = the account that deployed App ID 770956001.",
        "ADMIN_MNEMONIC=word1 word2 word3 ... word25",
        "",
    ]
    for role, acct in accounts.items():
        env_lines.append(f"{role.upper()}_ADDRESS={acct['address']}")
        env_lines.append(f"{role.upper()}_MNEMONIC={acct['mnemonic']}")
        env_lines.append("")

    env_content = "\n".join(env_lines)
    try:
        with open(ENV_OUT, "w") as f:
            f.write(env_content)
        print(f"  ✅ Written to {ENV_OUT}")
    except FileNotFoundError:
        print(f"  ⚠️  Could not write to {ENV_OUT} (path may not exist yet).")
        print("  Printing to stdout instead:\n")
        print(env_content)

    print("\n" + "="*60)
    print("NEXT STEPS")
    print("="*60)
    print(f"1. Open {ENV_OUT}")
    print("2. Replace ADMIN_MNEMONIC with your deployer account mnemonic.")
    print("3. Fund the admin address if it has < 1 ALGO:")
    print("   https://bank.testnet.algorand.network")
    print("4. Run:  pytest pillar-1/smart_contract/tests/test_contract.py -v")
    print()


if __name__ == "__main__":
    main()